Static dispatch output correction
alibaba-aero/technical-interview pull request #17
Opened 2022-06-13 12:00 UTC by raminfarajpour

2022-06-13 12:06 UTC, mokarchi approved these changes

2022-06-17 11:30 UTC, hossein13m requested changes
There is a minor grammatical issue in this PR.

2022-06-17 11:30 UTC, hossein13m commented on backend/dotnet/questions/oop.md
> +    It is an Bar.
Consider changing this sentence to `It is a Bar`

2022-06-18 17:47 UTC, hossein13m approved these changes
thanks @raminfarajpour

2022-06-18 18:06 UTC, raminfarajpour commented
Thanks for mentioning @hossein13m 
I correct that grammatical problems and some other problems in dynamic dispatch output

2022-07-11 20:33 UTC, hossein13m approved these changes

2022-07-14 12:31 UTC, MoienTajik approved these changes

2022-07-14 12:31 UTC, merged